apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f4hn2olb0-python 
  janus-idp.io/tekton: f4hn2olb0-python
  backstage.io/kubernetes-id: f4hn2olb0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f4hn2olb0-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  